# Generated by Django 2.1 on 2019-06-04 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SharedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalpath', models.CharField(max_length=100)),
                ('originalname', models.CharField(max_length=200)),
                ('evalue', models.CharField(max_length=32)),
                ('viewed', models.BooleanField(default=False)),
                ('shareddate', models.DateTimeField()),
                ('expirylength', models.CharField(max_length=5)),
                ('expirydate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('reference_name', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='who', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='sharedrecord',
            name='ereciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='file.UserRecord'),
        ),
        migrations.AddField(
            model_name='sharedrecord',
            name='esender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='file.UserRecord'),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
    ]
