# Generated by Django 2.1 on 2019-06-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('reference_name', models.CharField(max_length=32)),
                ('fileto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='which', serialize=False, to='file.File')),
            ],
            options={
                'ordering': ['reference_name'],
            },
        ),
    ]
