# Generated by Django 2.1 on 2019-06-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_filerecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedrecord',
            options={'ordering': ['-expirydate']},
        ),
        migrations.AddField(
            model_name='sharedrecord',
            name='copypath',
            field=models.CharField(default='', max_length=100),
        ),
    ]
