# Generated by Django 2.1 on 2019-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20190607_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedrecord',
            name='linkcount',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
