# Generated by Django 2.1 on 2019-06-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_sharedrecord_linkcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedrecord',
            name='copyname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
