# Generated by Django 2.1 on 2019-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_sharedrecord_copyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedrecord',
            name='contenthash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sharedrecord',
            name='ekey',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sharedrecord',
            name='pathhash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sharedrecord',
            name='reciever',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sharedrecord',
            name='sender',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sharedrecord',
            name='copyname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sharedrecord',
            name='copypath',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sharedrecord',
            name='originalname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sharedrecord',
            name='originalpath',
            field=models.CharField(max_length=255),
        ),
    ]
