# Generated by Django 2.1 on 2019-06-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_auto_20190612_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedrecord',
            name='evalue',
        ),
    ]
