# Generated by Django 2.1 on 2019-06-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_remove_sharedrecord_evalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedrecord',
            name='linkidentifier',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
