# Generated by Django 2.1 on 2019-06-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_auto_20190612_1433'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedrecord',
            unique_together=set(),
        ),
    ]
