# Generated by Django 2.1 on 2019-06-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_auto_20190612_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedrecord',
            name='ereciever',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='file.UserRecord'),
        ),
        migrations.AlterField(
            model_name='sharedrecord',
            name='esender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='file.UserRecord'),
        ),
    ]
