# Generated by Django 2.1 on 2019-06-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_auto_20190613_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerecord',
            name='fileto',
        ),
        migrations.RemoveField(
            model_name='userrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sharedrecord',
            name='ereciever',
        ),
        migrations.RemoveField(
            model_name='sharedrecord',
            name='esender',
        ),
        migrations.DeleteModel(
            name='FileRecord',
        ),
        migrations.DeleteModel(
            name='UserRecord',
        ),
    ]
