# Generated by Django 2.1 on 2019-06-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_auto_20190613_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedrecord',
            name='contenthash',
        ),
    ]
