# Generated by Django 2.1 on 2019-06-14 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0014_remove_sharedrecord_contenthash'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedrecord',
            name='contenthash',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
